---
all:
  hosts:
    k8s-master-1:
      ansible_host: 192.168.56.101
      ip: 192.168.56.101
      access_ip: 192.168.56.101
    k8s-master-2:
      ansible_host: 192.168.56.102
      ip: 192.168.56.102
      access_ip: 192.168.56.102
    k8s-master-3:
      ansible_host: 192.168.56.103
      ip: 192.168.56.103
      access_ip: 192.168.56.103
    k8s-node-1:
      ansible_host: 192.168.56.111
      ip: 192.168.56.111
      access_ip: 192.168.56.111
    k8s-node-2:
      ansible_host: 192.168.56.112
      ip: 192.168.56.112
      access_ip: 192.168.56.112
    k8s-node-3:
      ansible_host: 192.168.56.113
      ip: 192.168.56.113
      access_ip: 192.168.56.113
  children:
    kube_control_plane:
      hosts:
        k8s-master-1:
        k8s-master-2:
        k8s-master-3:
    kube_node:
      hosts:
        k8s-node-1:
        k8s-node-2:
        k8s-node-3:
    etcd:
      hosts:
        k8s-master-1:
        k8s-master-2:
        k8s-master-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
