---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/nginx
    type: DirectoryOrCreate
