---
apiVersion: v1
kind: Pod
metadata:
  name: pod-default
  namespace: default
spec:
  serviceAccountName: smutel
  containers:
    - image: alpine:latest
      name: alpine
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: smutel-token
  volumes:
    - name: smutel-token
      secret:
        secretName: smutel-secret
