---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  publishNotReadyAddresses: true
  ports:
    - name: intra
      protocol: TCP
      port: 7000
      targetPort: intra
    - name: tls
      protocol: TCP
      port: 7001
      targetPort: tls
    - name: jmx
      protocol: TCP
      port: 7199
      targetPort: jmx
    - name: jmxprometheus
      protocol: TCP
      port: 7070
      targetPort: jmxprometheus
    - name: cql
      protocol: TCP
      port: 9042
      targetPort: cql
  clusterIP: None
  selector:
    app: cassandra
