#!/bin/bash

set -euo pipefail

ARGUMENT_LIST=(
  "target"
  "folder"
  "grep"
  "igrep"
)

TARGET_LIST=(
  "vsphere"
  "aws"
)

grep=""
igrep=""

clean_image_aws() {
  local folder=$1
  local tag="Folder"

  local amis=$(aws ec2 describe-images --owners self --filters "Name=tag:${tag},Values=${folder}" --query 'Images[*].{ImageId:ImageId,Name:Name,SnapshotId:BlockDeviceMappings[*].Ebs.SnapshotId}')
  local amis_count=$(echo ${amis} | jq 'length')
  local amis_to_remove=""
  local snapshots_to_remove=""
  for ((i=0;i < ${amis_count};i++)) {
    local ami_id=$(echo ${amis} | jq .[$i].ImageId | xargs)
    local ami_name=$(echo ${amis} | jq .[$i].Name | xargs)
    local ami_snapshot=$(echo ${amis} | jq -r .[$i].SnapshotId[] | xargs)
    if [[ -n "${grep}" ]]; then
      if [[ -n "${igrep}" ]]; then
        if echo "${ami_name}" | grep -q "${grep}" && ! echo "${ami_name}" | grep -q "${igrep}"; then
          amis_to_remove="${amis_to_remove} ${ami_id}"
          snapshots_to_remove="${snapshots_to_remove} ${ami_snapshot}"
        fi
      else
        if echo "${ami_name}" | grep -q "${grep}"; then
          amis_to_remove="${amis_to_remove} ${ami_id}"
          snapshots_to_remove="${snapshots_to_remove} ${ami_snapshot}"
        fi
      fi
    elif [[ -n "${igrep}" ]]; then
      if [[ -n "${grep}" ]]; then
        if echo "${ami_name}" | grep -q "${grep}" && ! echo "${ami_name}" | grep -q "${igrep}"; then
          amis_to_remove="${amis_to_remove} ${ami_id}"
          snapshots_to_remove="${snapshots_to_remove} ${ami_snapshot}"
        fi
      else
        if ! echo "${ami_name}" | grep -q "${igrep}"; then
          amis_to_remove="${amis_to_remove} ${ami_id}"
          snapshots_to_remove="${snapshots_to_remove} ${ami_snapshot}"
        fi
      fi
    else
      amis_to_remove="${amis_to_remove} ${ami_id}"
      snapshots_to_remove="${snapshots_to_remove} ${ami_snapshot}"
    fi
  }

  echo "$(echo ${amis_to_remove} | wc -w) amis found to remove"
  for ami in ${amis_to_remove}; do
    echo "Deregistering ami ${ami} ..."
    aws ec2 deregister-image --image-id "${ami}"
  done

  if [[ $(echo ${amis_to_remove} | wc -w) != 0 ]]; then
    echo "Waiting a little bit before removing the snapshots"
    sleep 10
  fi

  echo "$(echo ${snapshots_to_remove} | wc -w) snapshots found to remove"
  for snapshot in ${snapshots_to_remove}; do
    echo "Deleting snapshot ${snapshot} ..."
    aws ec2 delete-snapshot --snapshot-id "${snapshot}"
  done
}

clean_image_vsphere() {
  local folder=$1

  local templates="$(govc find . -type m -runtime.powerState poweredOff -config.template true | grep "/${folder}/" | xargs || true)"
  local templates_to_remove=""
  for template in ${templates}; do
    local template_name=${template##*/}
    if [[ -n "${grep}" ]]; then
      if [[ -n "${igrep}" ]]; then
        if echo ${template_name} | grep -q "${grep}" && ! echo ${template_name} | grep -q "${igrep}"; then
          templates_to_remove="${templates_to_remove} ${template_name}"
        fi
      else
        if echo ${template_name} | grep -q "${grep}"; then
          templates_to_remove="${templates_to_remove} ${template_name}"
        fi
      fi
    elif [[ -n "${igrep}" ]]; then
      if [[ -n "${grep}" ]]; then
        if echo ${template_name} | grep -q "${grep}" && ! echo ${template_name} | grep -q "${igrep}"; then
          templates_to_remove="${templates_to_remove} ${template_name}"
        fi
      else
        if ! echo ${template_name} | grep "${igrep}"; then
          templates_to_remove="${templates_to_remove} ${template_name}"
        fi
      fi
    else
      templates_to_remove="${templates_to_remove} ${template_name}"
    fi
  done

  echo "$(echo ${templates_to_remove} | wc -w) templates found to remove"
  for template in ${templates_to_remove}; do
    echo "Removing template ${template} ..."
    govc vm.destroy ${template}
  done
}

usage() {
  local target_count=${#TARGET_LIST[*]}

  echo -n "Usage: clean_images [--target <"
  for (( i=0; i < $target_count; i++ )); do
    echo -n "${TARGET_LIST[$i]}"
    if [[ $i -ne $((target_count - 1)) ]]; then
      echo -n "|"
    fi
  done
  echo ">] [--grep <string>] [--igrep <string>] --folder <folder_name>"
}

help() {
  local target_count=${#TARGET_LIST[*]}

  usage
  echo ""
  echo "Arguments :"
  echo "--target"
  echo -n "    specify where you would like to remove images ("
  for (( i=0; i < $target_count; i++ )); do
    echo -n "${TARGET_LIST[$i]}"
    if [[ $i -ne $((target_count - 1)) ]]; then
      echo -n ", "
    fi
  done
  echo ")"
  echo "--grep"
  echo "    remove only image with name containing this string"
  echo "--igrep"
  echo "    remove all images except those containing this string"
  echo "--folder"
  echo "    specify in which folder you would like to remove images"
}

main() {
  if ! which aws > /dev/null; then
    echo "aws binary should be installed"
    exit 1
  fi

  if ! which govc > /dev/null; then
    echo "govc binary should be installed"
    exit 1
  fi

  if ! which jq > /dev/null; then
    echo "jq binary should be installed"
    exit 1
  fi

  if [[ -n "${VSPHERE_USER:-}" && -n "${VSPHERE_PASSWORD:-}" && -n "${VSPHERE_SERVER:-}" ]]; then
    export GOVC_URL="https://${VSPHERE_USER}:${VSPHERE_PASSWORD}@${VSPHERE_SERVER}/sdk"
    export GOVC_INSECURE=1
  fi

  if [[ -n "${AWS_REGION:-}" ]]; then
    export AWS_DEFAULT_REGION="${AWS_REGION}"
  fi

  opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}"),help" \
    --name "$(basename "$0")" \
    --options "" \
    -- "$@"
  )

  eval set --$opts

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --target)
          target=$2
          shift 2
          ;;
      --folder)
          folder=$2
          shift 2
          ;;
      --grep)
          grep=$2
          shift 2
          ;;
      --igrep)
          igrep=$2
          shift 2
          ;;
      --help)
          help
          exit 1
          ;;
      *)
          break
          ;;
    esac
  done

  if [[ -z "${folder:-}" ]]; then
    usage
    exit 1
  fi

  if [[ -n "${target:-}" ]]; then
    if declare -f clean_image_${target} > /dev/null; then
      clean_image_${target} ${folder}
    else
      echo "No function defined to remove images on ${target}"
      exit 1
    fi
  else
    for target in ${TARGET_LIST[@]}; do
      clean_image_${target} ${folder}
    done
  fi
}
main $@
